//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProFootball.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int PlayerID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Nationality { get; set; }
        public string Club { get; set; }
        public int Age { get; set; }
        public int Price { get; set; }
        public int PositionID { get; set; }
    
        public virtual PlayerPosition PlayerPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
